name: Build Python Executable

on:
  # 可根据需求修改触发条件，这里设置为推送到 master 分支时触发
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: windows-latest  # 指定使用 Windows runner

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: pyside6-demo
          path: ./dist

      - name: Checkout code
        run: dir .

      # 打包并发布到 GitHub Releases
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: CHANGELOG.md
          files: |
            dist
            CHANGELOG.md
